// Source: spec Step 6 + Updated d100 Red Text List.docx (May 2026 revision).
// d100 → red text. Indexed by roll-1.
export interface RedTextEntry {
  title: string;
  effect: string;
}

export const RED_TEXT: ReadonlyArray<RedTextEntry> = [
  { title: 'The One', effect: 'You may only fire this weapon once. It deals x10 Damage. It is then permanently destroyed.' },
  { title: 'Hot Diggity Dog', effect: 'Your ammo turns into chili-cheese slathered hotdogs. +1d8 Fire Damage.' },
  { title: 'Woo! Never Miss!', effect: '+2d4 Kinetic Damage. If you miss an attack with this gun, take 2d6 Embarrassment Damage.' },
  { title: 'Sick Kickflip', effect: 'While equipped, gain +2 to all Reflex Checks.' },
  { title: 'That’s a Winger guarantee', effect: '+5 Kinetic Damage to all enemies who are flying.' },
  { title: 'Gun of Flying', effect: 'Ignore Difficult Ground as you float four inches off the floor at all times.' },
  { title: 'Inconsistent footwork', effect: 'After you attack with this weapon, dance to an unoccupied adjacent Square.' },
  { title: '360 noscope', effect: 'Gain +2 Speed if you kill an enemy with this weapon until the end of your turn.' },
  { title: 'You’re Breathtaking!', effect: 'Enemies will not harm you during the first round of combat.' },
  { title: 'Screaming Steel', effect: 'Every time you fire this gun it emits a bloodcurdling scream. +3 to Diplomacy Checks made to Intimidate after firing.' },
  { title: 'Duck Hunt', effect: 'Each time you fire this weapon, there is a 20% chance it fires an explosive rubber duck, instead of the regular attack, dealing 4d6 Fire Damage (Splash 1).' },
  { title: 'Bark and Bite', effect: 'Your gun is now a dog. It barks when fired, bites when you miss, and loves you unconditionally: +3 Kinetic Damage, +1 Good Boy.' },
  { title: 'Recoil? What recoil?', effect: "This weapon has no kickback. In fact, you get pulled slightly toward whatever you're shooting at (Pull 1)." },
  { title: 'Big Iron', effect: 'If used before the target in the first round of combat, this weapon deals +1d12 Kinetic Damage.' },
  { title: 'You’re Already Dead.', effect: 'When you hit a Grunt-Tagged enemy, they take no damage... until they move. Then they explode (+2d12 Fire Damage, plus all additional Damage).' },
  { title: 'Nanite Roulette', effect: 'Each time you fire, roll 1d10. On a 1, your gun turns into a completely different gun type for 1 minute.' },
  { title: 'Sticky Situation', effect: 'This gun adheres to your hand. You literally cannot drop it.' },
  { title: 'Strange Aftertaste', effect: 'After killing an enemy, licking the barrel of this gun has a 50% chance to heal you for 1d6 Shields, or deal 1d6 Fire Damage to you.' },
  { title: 'Proud Mother', effect: 'This gun is sentient and loves to shout reassurances every time you miss an attack. +1 to Willpower Checks.' },
  { title: 'Tactical Slide', effect: 'Every time you fire, you automatically perform a stylish slide in a chosen direction (1 Square).' },
  { title: 'AI Assistant', effect: 'This gun has an onboard AI that comments on your combat performance. It is very critical. -2 to Willpower Checks, +2 to Mind Checks.' },
  { title: 'Friendly Firearms', effect: 'The gun likes your allies too much. If you miss on an attack with this weapon, it automatically fires at the nearest ally instead (Roll to hit again at an ally).' },
  { title: 'Gun Gremlins', effect: 'This weapon contains tiny gremlins. They reload for you, but will sometimes demand payment in food. +2 Kinetic Damage, -1 Snacks.' },
  { title: 'Excited Ambusher', effect: 'Whenever you fire, you also let out an involuntary shout. This makes stealth impossible, but it sounds really cool. -10 Shadow, +2 Kinetic Damage, +5 Kinetic Damage to a Surprised Enemy.' },
  { title: 'POP POP!', effect: 'Enemies slain by this weapon drop an additional Loot Pile.' },
  { title: 'Workweek Blues', effect: 'This gun refuses to fire on Mondays. Every other day of the week gains +2 Cold Damage.' },
  { title: 'Fingerguns Pro Max 15', effect: 'This weapon turns into an actual finger gun. Bullets are still real, but it looks ridiculous. -2 Diplomacy, +2 Kinetic Damage.' },
  { title: 'Announcer Mode', effect: 'Every shot is narrated by an invisible sports commentator, including slow-motion replays of your worst misses. -2 Willpower Checks, +2 Might Checks.' },
  { title: 'Budget Teleporter', effect: 'Every time you miss, you teleport 1d6 squares in a random direction. Hope you weren’t near a cliff.' },
  { title: 'Ghost Rounds', effect: 'This gun refuses to deal damage to Undead-Tagged enemies. However, it gains +5 Kinetic Damage against all other Tags.' },
  { title: 'I Cast Fist', effect: 'After making a melee attack, this gun deals double damage to the same target.' },
  { title: 'Gun Gremlins 2: The Sequel', effect: 'The gremlins inside this gun now have union demands. Every time you Miss with this gun, 5g disappears from your wallet. If you have no gold, the gun goes on strike and refuses to fire until it is paid.' },
  { title: 'Quantum Entanglement', effect: 'Every time you fire, one random person in the galaxy also fires a gun. Who? No idea.' },
  { title: 'Hamstrung by the Meta', effect: 'This weapon is nerfed every third shot, reducing its damage by 50%. Then, it is buffed to deal 200% damage for the fourth shot. Then it is nerfed back to normal. This cycle repeats endlessly as the weapon’s creator tries to keep the gun relevant.' },
  { title: 'Violent Therapy', effect: 'When you kill an enemy, the weapon gently reassures you, “You’re doing great, sweetie!” Misses prompt a softer, “It’s okay, take your time.”  +2 to Willpower Checks.' },
  { title: 'Proximity Chat Enabled', effect: 'Your gun automatically transmits any insults you shout at enemies directly into their comms. +2 Diplomacy and +1 Intimidation.' },
  { title: 'Absolutely Silent', effect: 'This gun makes no noise at all. Not even a click. It’s actually kind of unsettling. +4 Shadow.' },
  { title: 'The Gentleman’s Sport', effect: 'Every Critical Hit with this gun is accompanied by the sound of a polite golf clap. +1d8 True Damage on a Critical Hit.' },
  { title: 'Reality Lag', effect: 'Damage from this gun is delayed until the start of your next turn. Enemies won’t realize they’ve been shot until it catches up.' },
  { title: 'Surprise Mechanics', effect: 'Every shot has a 5% chance of generating a small cache of loot.' },
  { title: 'The Gun That Whispers', effect: 'At night, this weapon whispers in your ear. It says your name. It knows things. +2 to Willpower Checks.' },
  { title: 'Wraithshot', effect: 'Killing an enemy with this weapon raises their ghost. The ghost won’t attack, but it will follow you forever, haunting you.' },
  { title: 'Gun of the Nameless King', effect: '+1d8 Volt Damage. Every time you kill with this gun, you must roll 1d100. On a 1, your name is erased from history.' },
  { title: 'Cursebound Barrel', effect: 'Attacking a Cursed target deals an extra 1d8 Entropy Damage.' },
  { title: 'Taste the Painbow', effect: 'The barrel is a swirl of multi-colours. Every time you fire this weapon, roll 1d6 to determine what Damage type is fired from the gun: 1-2 Kinetic, 3 Acid, 4 Cold, 5 Fire, 6 Volt.' },
  { title: 'Mana Leak', effect: 'Your Willpower Score is reduced by 4 as long as this weapon is equipped. Spells you cast cost -2 Momentum Points (Minimum 1).' },
  { title: 'Door-Hater', effect: 'If you shoot a locked door, chest, or other traditionally-locked object with this gun, there is a 5% chance you unlock the object instead of dealing damage to it.' },
  { title: 'Enchanting Tracers', effect: 'Each shot leaves behind trails of glowing light that last 1 minute. It’s great for drawing shapes in the air.' },
  { title: 'But I’m not a Rapper', effect: 'You must hold the gun sideways. +5 Style and +2 (Red-Hot) Fire Damage.' },
  { title: 'Sponsored by Lizard-Chicken BucketTM', effect: 'This gun clucks like a chicken with every shot. Whenever you miss, a free drumstick is dispensed that heals 1 Shield Health. The barrel is covered in sponsorship stickers.' },
  { title: 'Boomer Energy', effect: 'This gun gains Splash 1. Whenever you fire this weapon, it complains about how weapons were better back in its day.' },
  { title: 'Legally a War Crime', effect: 'Every time you fire, at least one government somewhere adds you to a watchlist. +1d6 Acid Damage.' },
  { title: 'Wanted in 12 Systems', effect: 'This gun is banned in more places than it is legal. Every shot adds +10g to your intergalactic bounty. Eventually, someone may come to claim it... +2 Acid Damage.' },
  { title: 'Gun, but worse...', effect: 'No modifications. Nothing special. It just feels… kinda bad to use.' },
  { title: 'The Ultimate Counter', effect: 'If this gun is fired during a villainous monologue, deal double damage.' },
  { title: "Shields? Nah, I'm Good.", effect: 'This gun actively mocks you for having shields. Gain +1d6 Kinetic Damage, but take 1d4 Emotional Damage every time you take Damage to your Shield.' },
  { title: 'Explosive Mag', effect: 'After firing this gun 10 times, it explodes, dealing 2d10 Fire Damage the wielder and adjacent targets. It is permanently destroyed.' },
  { title: 'Nostalgia Blaster', effect: 'Fires retro laser beams accompanied by 8-bit sound effects. Crits play a victory jingle. +4 Plasma Damage.' },
  { title: 'Spacer’s Guide to Mediocrity', effect: 'Every shot comes with a fun fact about space. Unfortunately, the facts are 90% wrong. -1 to Mind Checks, +1 to Willpower Checks.' },
  { title: 'Clutch or Kick', effect: 'When you’re the only ally not Downed or Dead in combat, this weapon gains +4d10 Kinetic Damage, but also makes you feel crushing existential pressure.' },
  { title: 'Gally’s Horn', effect: 'Shots fired play dramatic music that crescendo on impact with the target. Gain Splash 2.' },
  { title: 'Master of Raven’s Lofty House', effect: 'Gain Transfusion 1.' },
  { title: 'Threat Level Midnight', effect: 'Critical hits cause your weapon to glow gold and play dramatic music. +1d6 Cold Damage.' },
  { title: 'Unbreakable Assistant', effect: 'Critical hits inflict Broken 1 on the target. However, it constantly says, “Fact: This weapon is superior to all others.”' },
  { title: 'Darkest Timeline Edition', effect: 'This weapon sports a tiny felt goatee. It deals +1d6 Dark Damage, but you must roll a Mind Check (DC 10) to avoid maniacal laughter after a critical hit.' },
  { title: 'Winter is Coming', effect: '+1d6 Cold Damage. On a critical hit, the gun whispers “For space is dark and full of terrors.”' },
  { title: 'Jonathan Wycks’ Weapon', effect: '+2 Kinetic Damage against enemies who’ve harmed your allies. On your first kill in combat, the weapon whispers “He’s back.”  +2 to Might Checks.' },
  { title: 'Marcille’s Nightmare', effect: '+ 2 Fire Damage. Beast-Tagged enemies drop roasted meat that restores 1 Health when slain by this gun, alongside regular loot.' },
  { title: 'Nice. Just… Nice.', effect: 'Every time you roll a critical hit with this weapon, it whispers, “Nice.”  +3 to Diplomacy Checks.' },
  { title: 'Eepy', effect: 'Enemies hit lose -1 to their Speed until the end of their next turn.' },
  { title: 'Jealous Much!?', effect: 'If you fire with another equipped gun, you take 1d6 Slashing Damage. If you fire with another gun, then fire with this gun on your next turn, gain +1d10 Kinetic Damage.' },
  { title: 'The Dad Joke Destroyer', effect: 'Critical hits with this weapon force the bearer to make bad puns, such as, “What happens to an illegally parked frog? It gets toad.” Allies within 6 Squares take 1d4 Cringe Damage, enemies within 6 Squares take 1d8 Cringe Damage.' },
  { title: 'Single Bots in your System', effect: 'Each critical hit generates a barrage of holographic popup ads for “Totally legitimate,” products and services. Enemies hit must make a DC 8 Willpower Check or gain Stunned 1, because they can’t close the windows fast enough.' },
  { title: 'Pocket Sand Dispenser', effect: "This gun gains Pocket Sand: 1 AP, 2 MP, Attack Action. Target must make a DC 12 Reflex Check or gain Blinded 1. This weapon can spray sand in enemies' faces. Deals no damage, but applies Blinded 1 because, let’s be honest, no one’s ready for pocket sand." },
  { title: 'Paperclip’s Revenge', effect: 'When you aim, a holographic assistant pops up: “It looks like you’re trying to kill something! Need help?” On a critical miss, it adds, “You could’ve used some pointers.”  +2d4 Plasma Damage.' },
  { title: 'The Dead Wolf’s Howl', effect: 'Killing an enemy leaves behind a spectral scythe that floats for 1 round. Allies within 3 Squares of the scythe gain +2 to Damage rolls as the Dead Wolf looms near.' },
  { title: 'Six Feet First', effect: 'Killing an enemy with this gun causes the ground beneath them to collapse into an instant grave when standing on a planet’s surface. Allies can’t help but admire the convenience. +1d6 Entropy Damage.' },
  { title: 'Math, O Nyo!', effect: 'If it takes more than thirty seconds for you to total up your damage after attacking with this gun, you lose -10 to your total damage. Otherwise, gain +1d6 Cold Damage.' },
  { title: 'I’m Wet', effect: 'If you are standing in any kind of liquid at the start of your turn, you gain +1d8 Shields.' },
  { title: 'That’s what it do, Yugi!', effect: 'If you kill an enemy with a this gun, it drops +2 Loot Piles.' },
  { title: 'Bullets of Revealing Light', effect: 'You can shoot an ally once per Full Rest, dealing no damage and granting them Invincible 3.' },
  { title: 'The High Ground', effect: 'If you’re attacking from an elevated position, this weapon deals +2d6 Damage. Critical hits cause the weapon to exclaim, “It’s over!”' },
  { title: 'The Bees!', effect: 'Every time you fire this weapon, fire-bees erupt from the gun. They deal 1d8 Fire Damage to all adjacent targets.' },
  { title: 'I Never Die', effect: 'Using your Ultimate grants you +2d10 Shields.' },
  { title: 'The Clapper', effect: 'This weapon only fires when you clap twice. It’s as hilarious as it is inefficient. +2 Plasma Damage.' },
  { title: 'Do You Even Lift?', effect: '+2 to Might Checks when holding this weapon, but it constantly critiques your form.' },
  { title: 'Comedic Timing', effect: 'Every shot is accompanied by a random sound effect, ranging from trombones to slide whistles. On a critical hit, expect a standing ovation from your weapon. +5 Light Damage.' },
  { title: 'Live, Laugh, Ladle', effect: 'On a critical hit, allies within 3 Squares gain +1 Shields as the gun emanates the faint smell of homemade soup.' },
  { title: 'Toon Blaster', effect: 'Shots create cartoonish effects, like oversized anvils or puffs of smoke. Critical hits cause enemies to shrink and deal -5 Damage for one round.' },
  { title: 'Assistant (to the) Regional Manager', effect: "If you’re in a group, this weapon grants +1 Kinetic Damage. If you're alone, it deals -2 Damage because it “thrives on teamwork.”" },
  { title: 'Duel of the Fated', effect: 'Killing a non-Minion Tagged enemy triggers a faint orchestral soundtrack as the weapon pulses with energy, granting you an additional +1 Momentum. Critical hits feel strangely epic.' },
  { title: 'Final Boss Energy', effect: 'Critical hits cause dramatic music to swell. For the next turn, your Damage rolls gain +4, but your enemies roll with Advantage to counter your main character vibes.' },
  { title: 'The Procrastinator', effect: 'Deals +3d6 Kinetic Damage, but it only works on your final Action Point each turn.' },
  { title: 'Druid’s Companions', effect: 'Each time you reload, a random woodland creature assists you by distracting the enemy. +4 Light Damage to your next Damage Roll, but you feel bad about sending the squirrel into combat.' },
  { title: 'A Pencil Would’ve Done', effect: 'If you miss with this weapon, you may make a free Melee Attack using the butt of this weapon, dealing 1d6 Kinetic Damage on a minor, major, or grave hit to an adjacent target.' },
  { title: 'Delicious Firepower', effect: 'You can eat this weapon to regain 2d6 HP. It is then permanently destroyed.' },
  { title: 'Soul Tether', effect: 'Enemies killed with this weapon leave behind a glowing tether to you. At the start of your next turn, you regain +1d6 Shields for each tether.' },
  { title: 'Shaaaaaaaaaark!', effect: 'The bullets resemble tiny sharks and occasionally let out high-pitched roars. On a critical hit, the weapon declares, “Shaaark!”  +3 Cold Damage.' },
  { title: 'Wrath of the Forbidden One', effect: 'Killing five enemies that are above the Minion rank in one combat encounter causes the weapon to summon the incalculable and intimidating might of The Forbidden One, obliterating a target of your choice within 10 Squares for 1000 Chosen Damage Type. The weapon yells, “OBLITERATE!”' },
  { title: 'Uncle Roger’s Expectations', effect: 'This weapon always deals maximum damage on every roll. The downside? It refuses to let you use any other gun or melee weapon and constantly critiques your aim. If you attempt to use another weapon, you take 6d12 Emotional Damage.' },
];
