// Source: spec Step 6. d100 → red text. Indexed by roll-1.
export interface RedTextEntry {
  title: string;
  effect: string;
}

export const RED_TEXT: ReadonlyArray<RedTextEntry> = [
  { title: 'The One', effect: 'You may only fire this weapon once. It deals x10 Damage. It is then permanently destroyed.' },
  { title: 'Hot Diggity Dog', effect: 'Your ammo turns into chili-cheese slathered hotdogs. +1d8 Fire Damage.' },
  { title: 'Woo! Never Miss!', effect: '+2d4 Kinetic Damage. If you Miss an attack with this gun, take 2d6 Embarrassment Damage.' },
  { title: 'Sick Kickflip', effect: 'While equipped, gain +2 to all Reflex Checks.' },
  { title: "That's a Winger guarantee", effect: '+5 Kinetic Damage to all enemies who are flying.' },
  { title: 'Gun of Flying', effect: 'Ignore Difficult Ground as you float four inches off the floor at all times.' },
  { title: 'Inconsistent footwork', effect: 'After you attack with this weapon, teleport to an unoccupied adjacent Square.' },
  { title: '360 noscope', effect: 'Gain +2 Speed if you kill an enemy with this weapon for this turn.' },
  { title: "You're Breathtaking!", effect: 'Enemies will not harm you during the first round of combat.' },
  { title: 'Screaming Steel', effect: 'Every time you fire this gun it emits a bloodcurdling scream. +3 to Diplomacy Checks made to Intimidate after firing.' },
  { title: 'Duck Hunt', effect: 'Each time you fire this weapon, there is a 20% chance it fires an explosive rubber duck dealing 4d6 Fire Damage (Splash 1).' },
  { title: 'Bark and Bite', effect: 'Your gun is now a dog. It barks when fired, bites when you miss, and loves you unconditionally: +3 Kinetic Damage, +1 Good Boy.' },
  { title: 'Recoil? What recoil?', effect: "This weapon has no kickback. In fact, you get pulled slightly toward whatever you're shooting at (Pull 1)." },
  { title: 'Big Iron', effect: 'If used before the target in the first round of combat, this weapon deals +1d12 Kinetic Damage.' },
  { title: "You're Already Dead.", effect: 'When you hit a Grunt or Elite-Tagged enemy, they take no damage... until they move. Then they explode (+2d12 Fire Damage, plus all additional Damage).' },
  { title: 'Nanite Roulette', effect: 'Each time you fire, roll 1d10. On a 1, your gun turns into a completely different gun type for 1 minute.' },
  { title: 'Sticky Situation', effect: 'This gun adheres to your hand. You literally cannot drop it.' },
  { title: 'Strange Aftertaste', effect: 'After killing an enemy, licking the barrel has a 50% chance to heal 1d6 Shields or deal 1d6 Fire Damage to you.' },
  { title: 'Proud Mother', effect: 'This gun is sentient and loves to shout reassurances every time you miss an attack. +1 to Willpower Checks.' },
  { title: 'Tactical Slide', effect: 'Every time you fire, you automatically perform a stylish slide in a chosen direction (1 Square).' },
  { title: 'AI Assistant', effect: 'This gun has an onboard AI that comments on your combat performance. It is very critical. -2 to Willpower Checks, +2 to Mind Checks.' },
  { title: 'Friendly Firearms', effect: 'If you Miss on an attack, it automatically fires at the nearest ally instead (Roll to hit again).' },
  { title: 'Gun Gremlins', effect: 'This weapon contains tiny gremlins. They reload for you, but will sometimes demand payment in food. +2 Kinetic Damage, -1 Snacks.' },
  { title: 'Excited Ambusher', effect: 'Whenever you fire, you let out an involuntary shout. Stealth impossible. -10 Shadow, +1 Kinetic Damage, +5 Kinetic Damage to a Surprised Enemy.' },
  { title: 'POP POP!', effect: 'Enemies slain by this weapon drop an additional Loot Pile.' },
  { title: 'Workweek Blues', effect: 'This gun refuses to fire on Mondays. Every other day of the week gains +2 Cold Damage.' },
  { title: 'Fingerguns Pro Max 15', effect: 'This weapon turns into an actual finger gun. Bullets are still real, but it looks ridiculous. -2 Diplomacy, +2 Kinetic Damage.' },
  { title: 'Announcer Mode', effect: 'Every shot is narrated by an invisible sports commentator. -2 Willpower Checks, +2 Might Checks.' },
  { title: 'Budget Teleporter', effect: 'Every time you Miss, you teleport 1d6 squares in a random direction.' },
  { title: 'Ghost Rounds', effect: 'This gun refuses to deal damage to Undead enemies. However, it gains +5 Kinetic Damage to all other targets.' },
  { title: 'I Cast Fist', effect: 'After making a melee attack, this gun deals double damage to the same target.' },
  { title: 'Gun Gremlins 2: The Sequel', effect: 'The gremlins now have union demands. Every Miss costs 5g. If you have no gold, the gun goes on strike.' },
  { title: 'Quantum Entanglement', effect: 'Every time you fire, one random person in the galaxy also fires a gun.' },
  { title: 'Hamstrung by the Meta', effect: 'Nerfed every 3rd shot (-50% damage). Buffed on 4th shot (+200%). Cycle repeats.' },
  { title: 'Violent Therapy', effect: 'On kill: "You\'re doing great, sweetie!" On miss: "It\'s okay, take your time." +2 to Willpower Checks.' },
  { title: 'Proximity Chat Enabled', effect: 'Automatically transmits your insults to enemies. +2 Diplomacy, +1 Intimidation.' },
  { title: 'Absolutely Silent', effect: 'This gun makes no noise at all. +4 Shadow.' },
  { title: "The Gentleman's Sport", effect: 'Every Critical Hit is accompanied by the sound of a polite golf clap.' },
  { title: 'Reality Lag', effect: 'Damage from this gun is delayed by 1 round.' },
  { title: 'Surprise Mechanics', effect: 'Every shot has a 5% chance of generating a random small cache of loot.' },
  { title: 'The Gun That Whispers', effect: 'At night, this weapon whispers in your ear. It says your name. It knows things. +2 to Willpower Checks.' },
  { title: 'Wraithshot', effect: 'Killing an enemy with this weapon raises their ghost. The ghost follows you forever.' },
  { title: 'Gun of the Nameless King', effect: '+1d8 Volt Damage. Every kill: roll 1d100. On a 1, your name is erased from history.' },
  { title: 'Cursebound Barrel', effect: 'Attacking a Cursed target deals an extra 1d8 Entropy Damage.' },
  { title: 'Taste the Painbow', effect: 'Every time you fire, roll 1d6: 1–2=Kinetic, 3=Acid, 4=Cold, 5=Fire, 6=Volt.' },
  { title: 'Mana Leak', effect: 'Willpower Score reduced by 4 while equipped. Spells cost -2 Momentum Points.' },
  { title: 'Door-Hater', effect: 'Shooting a locked object has a 50% chance to unlock it instead of dealing damage.' },
  { title: 'Enchanting Tracers', effect: 'Each shot leaves glowing trails that last 1 minute.' },
  { title: "But I'm not a Rapper", effect: 'Must hold the gun sideways. +5 Style, +2 Fire Damage.' },
  { title: 'Sponsored by Lizard-Chicken Bucket™', effect: 'Clucks on every shot. On a miss, dispenses a free drumstick that heals 1 Shield Health.' },
  { title: 'Boomer Energy', effect: 'Gun gains Splash 1. Complains about how weapons were better back in its day.' },
  { title: 'Legally a War Crime', effect: 'Every time you fire, a government adds you to a watchlist. +1d6 Acid Damage.' },
  { title: 'Wanted in 12 Systems', effect: 'Every shot adds +10g to your intergalactic bounty. +2 Acid Damage.' },
  { title: 'Gun, but worse...', effect: 'No modifications. Nothing special. It just feels… kinda bad to use.' },
  { title: 'The Ultimate Counter', effect: 'If fired during a villainous monologue, deal double damage.' },
  { title: "Shields? Nah, I'm Good.", effect: '+1d6 Kinetic Damage, but take 1d4 Emotional Damage every time you take Shield Damage.' },
  { title: 'Explosive Mag', effect: 'After firing 10 times, it explodes dealing 2d10 Fire Damage to wielder and adjacent targets. Permanently destroyed.' },
  { title: 'Nostalgia Blaster', effect: 'Fires retro laser beams with 8-bit sound effects. Crits play a victory jingle. +4 Plasma Damage.' },
  { title: "Spacer's Guide to Mediocrity", effect: 'Every shot comes with a fun fact about space (90% wrong). -1 Mind Checks, +1 Willpower Checks.' },
  { title: 'Clutch or Kick', effect: "When you're the only ally not Downed or Dead, this weapon gains +4d10 Kinetic Damage." },
  { title: "Gally's Horn", effect: 'Shots fired play dramatic music. Gain Splash 2.' },
  { title: "Master of Raven's Lofty House", effect: 'Gain Transfusion 1.' },
  { title: 'Threat Level Midnight', effect: 'Critical hits cause your weapon to glow gold and play dramatic music. +1d6 Cold Damage.' },
  { title: 'Unbreakable Assistant', effect: 'Critical hits inflict Broken 1 on the target. Constantly says "Fact: This weapon is superior to all others."' },
  { title: 'Darkest Timeline Edition', effect: 'Tiny felt goatee. +1d6 Dark Damage; roll Mind Check (DC 10) to avoid maniacal laughter after a crit.' },
  { title: 'Winter is Coming', effect: '+1d6 Cold Damage. On a crit, whispers "For space is dark and full of terrors."' },
  { title: "Jonathan Wycks' Weapon", effect: "+2 Kinetic Damage against enemies who've harmed your allies. First kill: whispers \"He's back.\" +2 Might Checks." },
  { title: "Marcille's Nightmare", effect: '+2 Fire Damage. Beast-Tagged enemies slain drop roasted meat restoring 1 Health alongside regular loot.' },
  { title: 'Nice. Just… Nice.', effect: 'Every crit, it whispers "Nice." +3 to Diplomacy Checks.' },
  { title: 'Eepy', effect: 'Enemies hit lose -1 to their Movement Score until end of their next turn.' },
  { title: 'Jealous Much!?', effect: 'Firing another equipped gun deals 1d6 Slashing Damage to you. Firing this gun next turn grants +1d10 Kinetic Damage.' },
  { title: 'The Dad Joke Destroyer', effect: 'Crits force the bearer to make bad puns. Allies within 6 Squares take 1d4 Cringe Damage; enemies take 1d8.' },
  { title: 'Single Bots in your System', effect: 'Crits generate holographic popup ads. Enemies hit: DC 8 Willpower Check or gain Stunned 1.' },
  { title: 'Pocket Sand Dispenser', effect: 'Fires sand instead of bullets. No damage, but applies Blinded 1.' },
  { title: "Paperclip's Revenge", effect: 'Holographic assistant pops up on aim. On crit miss: "You could\'ve used some pointers." +2d4 Plasma Damage.' },
  { title: "The Dead Wolf's Howl", effect: 'Killing an enemy leaves a spectral scythe for 1 round; Allies within 3 Squares gain +2 Damage.' },
  { title: 'Six Feet First', effect: 'Killing an enemy collapses the ground into an instant grave. +1d6 Entropy Damage.' },
  { title: 'Math, O Nyo!', effect: 'If damage takes more than 30 seconds to total, lose -10 to total damage. Otherwise, +1d6 Cold Damage.' },
  { title: "I'm Wet", effect: 'Standing in any liquid at start of turn grants +1d8 Shields.' },
  { title: "That's what it do, Yugi!", effect: 'Killing an enemy drops +2 Loot Piles.' },
  { title: 'Bullets of Revealing Light', effect: 'Shoot an ally once per Full Rest; deals no damage, grants Invincible 3.' },
  { title: 'The High Ground', effect: '+2d6 Damage when attacking from an elevated position. Crits: "It\'s over!"' },
  { title: 'The Bees!', effect: 'Every time you fire, fire-bees erupt dealing 1d8 Fire Damage to all adjacent targets.' },
  { title: 'I Never Die', effect: 'Using your Ultimate grants +2d10 Shields.' },
  { title: 'The Clapper', effect: 'This weapon only fires when you clap twice. +2 Plasma Damage.' },
  { title: 'Do You Even Lift?', effect: '+2 to Might Checks when holding this weapon, but it constantly critiques your form.' },
  { title: 'Comedic Timing', effect: 'Every shot accompanied by a random sound effect. Standing ovation on a crit. +5 Light Damage.' },
  { title: 'Live, Laugh, Ladle', effect: 'On a crit, allies within 3 Squares gain +1 Shields as the gun emits the faint smell of homemade soup.' },
  { title: 'Toon Blaster', effect: 'Shots create cartoonish effects. Crits cause enemies to shrink and deal -5 Damage for one round.' },
  { title: 'Assistant (to the) Regional Manager', effect: '+1 Kinetic Damage in a group. -2 Damage when alone (it "thrives on teamwork").' },
  { title: 'Duel of the Fated', effect: 'Killing an enemy triggers a faint orchestral soundtrack; gain +1 Momentum.' },
  { title: 'Final Boss Energy', effect: 'Crits: Damage rolls gain +4 for next turn, but enemies roll with Advantage to counter you.' },
  { title: 'The Procrastinator', effect: '+3d6 Kinetic Damage, but only works on your final Action Point each turn.' },
  { title: "Druid's Companions", effect: 'Each reload, a random woodland creature distracts an enemy. +4 Light Damage to next Damage Roll.' },
  { title: "A Pencil Would've Done", effect: 'On a Miss, make a free Melee Attack with the gun butt (1d6 Kinetic Damage on hit).' },
  { title: 'Delicious Firepower', effect: 'You can eat this weapon to regain 2d6 HP.' },
  { title: 'Soul Tether', effect: 'Enemies killed leave a glowing tether; regain +1d6 Shields per tether at start of your next turn.' },
  { title: 'Shaaaaaaaaaark!', effect: 'Bullets resemble tiny sharks. On a crit, the weapon declares "Shaaark!" +3 Cold Damage.' },
  { title: 'Wrath of the Forbidden One', effect: 'After killing 5 non-Minion enemies in one encounter, obliterate a target within 10 Squares for 1000 Chosen Damage. The weapon yells "OBLITERATE!"' },
  { title: "Uncle Roger's Expectations", effect: 'Always deals maximum damage. Cannot use any other weapon; attempting to do so deals 6d12 Emotional Damage.' },
];
