// Source: Lootbreaker_MeleeWeaponGeneration_Version0dot10.pdf — Step Six.
// d100 → red text. Indexed by roll-1. Titles and effects transcribed verbatim.

export interface RedTextEntry {
  title: string;
  effect: string;
}

export const RED_TEXT: ReadonlyArray<RedTextEntry> = [
  { title: 'We Get It, And That’s It!', effect: 'Only YOU can loot enemies you kill, until the end of time' },
  { title: 'Roses by the stairs', effect: 'When you loot an enemy you killed, you gain +2 HP' },
  { title: 'What’s New, Dog?', effect: 'Whenever you regain Shields or HP, you gain an additional +1 to the total' },
  { title: 'You know what zombies love more than brains?', effect: 'You deal an additional +3 Damage to Undead Targets' },
  { title: 'I’d Kiss Me', effect: 'Attacking with this weapon Taunts all enemies within 2 Squares' },
  { title: 'A Hot Metal Slide on a Summer’s Day', effect: 'You gain +3 Speed when sliding down surfaces, but take +1d6 Fire Damage' },
  { title: 'Slightly Tyrannical', effect: '+1 to Accuracy Rolls against Mini-Bosses' },
  { title: 'Corridor Debunked', effect: '+3 to Checks to determine the nature of Cryptids' },
  { title: 'Corridor Reacting', effect: '+3 to Checks used to examine recorded footage' },
  { title: 'Haiiiii', effect: '+5 Damage when attacking a foe unaware of your location' },
  { title: 'Ooze-y', effect: '+2 Acid Damage' },
  { title: 'Protective Father Figure', effect: 'When you Major or Grave Hit a target with this weapon, you gain +1 Shields' },
  { title: 'We Do Beg Your Pardon,', effect: 'But We Are In Your Garden, -2 Shadow, +2 Diplomacy.' },
  { title: 'I Need A Few Much More Money', effect: 'On a scale of one to ten can I borrow five gold? +5 Gold when you kill a target with this weapon.' },
  { title: 'We Got That Swamp Heat', effect: '+2 Acid and +2 Fire Damage with this weapon.' },
  { title: 'Ska Came Before Reggae', effect: 'Only because I allowed it. +3 to checks made involving musical instruments. +5 when trumpets are involved.' },
  { title: 'The Coconut Gods is Smilings on Me!', effect: '+5 HP when eating fruit.' },
  { title: 'I Want His Wallet, Gimmie!', effect: '+3 Shadow when attempting to pickpocket' },
  { title: 'Butt Butt Dick Diddick', effect: '+3 Damage when damaging a clone' },
  { title: 'You’re Too Low, Jon Crow', effect: '+3 Accuracy when attacking from below a target' },
  { title: 'Foodie Hater', effect: '+2 Damage when attacking a target holding, or eating, food' },
  { title: 'Bad With Names', effect: 'You never remember anyone’s name, -2 Diplomacy. There’s no bonus. Do better.' },
  { title: 'Hey, I’ve Seen This One Before!', effect: 'This weapon glows when near goblins, hobgoblins, or similar creatures.' },
  { title: 'Aerodynamic', effect: '+1 Throw Range' },
  { title: 'Skellykey', effect: 'You can open any locked door with this weapon once, then the weapon breaks' },
  { title: 'Crunchy', effect: '+2 Damage against stone or bone targets' },
  { title: 'Slippery When Wet', effect: '+3 Accuracy while submerged water or similar fluids' },
  { title: 'Turtle Power', effect: '+1 Accuracy and +1 Damage when underground' },
  { title: 'Can’t Park Here', effect: '+2 Damage against enemies riding vehicles' },
  { title: 'Socially Distant', effect: '-2 Diplomacy, +2 Damage' },
  { title: 'Carl’s Nightmare', effect: '+3 Damage when you aren’t wearing pants' },
  { title: 'Crawler', effect: 'You gain +1 to all Checks when you are crawling, +2 when you are crawling in a dungeon' },
  { title: 'For Those Who Come After', effect: '+33 Damage against painted structures or targets' },
  { title: 'Sponsored Segment', effect: 'A random Guild has sponsored this weapon. Whenever you do something that positively affects your Faction Score with this Guild, you gain +50 Gold' },
  { title: 'Big Bad Intro', effect: 'When a Boss enters the same room as you, you gain +5 Overshields' },
  { title: 'Gifted Subs', effect: 'Your weapon livestreams your battles. If you kill a Mini-Boss or higher tier enemy, you gain +50 Follows and an additional +200 Gold' },
  { title: 'Daddy Likes', effect: 'You gain +5 to all Damage rolls when you use your feet. No bonus if you don’t have feet.' },
  { title: 'Tax Evader', effect: '+1 to all Checks when fighting government officials' },
  { title: 'A Lot On Your Mind', effect: 'And well, IN it. Gain +2 to all Checks when you have a parasite or similar infection' },
  { title: 'Paranormal Relationship', effect: '+3 Diplomacy when interacting with ghosts, spirits, revenants, or other non-corporeal creatures' },
  { title: 'A Light Sword', effect: 'A Lightweight Sabre, even. +3 Plasma Damage' },
  { title: 'DLC Required', effect: 'This weapon may stop functioning until you buy the newest DLC from its creators. +1 Damage' },
  { title: 'Soul Powered', effect: 'Every time you kill a creature with this weapon, it gains +1 Soul Score. When it reaches 99, your next attack gains +99 Damage' },
  { title: 'Dear Maria, Count Me In', effect: 'Gain +2 to all Checks if you are drunk.' },
  { title: 'Newly Founded Glory', effect: 'Whenever you choose to heal your friends, you gain +2 Overshield' },
  { title: 'Ocean Avenue Resident', effect: '+2 to Accuracy Rolls when you are in water' },
  { title: 'Black Procession', effect: '+2 Accuracy against humanoids wearing black' },
  { title: 'A Simple Plan', effect: '+2 Search' },
  { title: 'Rise Against Them All', effect: '+2 Damage against Guild Members. Any Guild.' },
  { title: 'All Downhill From Here', effect: 'After being Downed, your next Check or Accuracy Roll gains a +2 bonus' },
  { title: 'Miss Murder', effect: 'After you Miss an Accuracy Roll with this weapon, gain a +2 bonus to your next Accuracy Roll' },
  { title: 'Paralyzer', effect: 'When you would gain the Stunned Condition, as a ReAction for 1 MP and 1 AP, you may instead take 1d12 Kinetic Damage and avoid the Condition' },
  { title: 'Para-more Pressure', effect: '+2 to Checks if you are separated by more than 15 Squares from any allies' },
  { title: 'Falling Out, Boi', effect: 'Gain +2 to all Checks when you are falling' },
  { title: 'All The Small Targets', effect: 'Gain 1d8 + 2 Damage against small targets' },
  { title: 'A Loot-a Slasher', effect: 'When you Lootbreak an item, deal 2d8 Slashing Damage to adjacent enemies' },
  { title: 'Baller', effect: 'Gain +2 to Checks related to throwing balls, or grenades. Anything spherical, really' },
  { title: 'Vlad Would Be Proud', effect: '+5 Overshield if you kill an enemy by impaling them on something sharp' },
  { title: 'Sting Like A Goo', effect: '+2 Acid Damage' },
  { title: 'Tinderbox', effect: '+2 Fire Damage' },
  { title: 'Shock and Aweee', effect: '+2 Volt Damage, +10 if you are attacking a cute and fuzzy creature' },
  { title: 'See Ya Later Boy', effect: '+2 to all Checks made to use a skateboard, or similar device' },
  { title: 'You’re HUGE', effect: '+1 to Accuracy Rolls with this weapon against targets bigger than you' },
  { title: 'Forget Me Not', effect: 'If you throw this weapon, you can use 1 MP to recall it to your hand from any distance (Wait times may vary)' },
  { title: 'Training Stick', effect: 'Your weapon looks like a tree branch. -2 Diplomacy, +2 World' },
  { title: 'Arms Like THESE!?', effect: 'When your Shield is depleted, you gain +4 to Diplomacy Checks' },
  { title: 'You Know Your Judo Well', effect: '+2 Unarmed Damage' },
  { title: 'A Succulent Outer Reaches Meal!?', effect: 'You gain +5 Overshield whenever you eat a delicious meal' },
  { title: 'Still Nice', effect: 'You’re that charming, +3 Diplomacy' },
  { title: 'Capitalism Manifest', effect: 'When you buy items from a shopkeeper or vending machine, you gain a 10% price increase. There’s no benefit. Think about it.' },
  { title: 'The Eye Of The Bride', effect: 'When you make a Search Check, you can risk a 5% chance to go permanently insane for Advantage' },
  { title: 'Hellfire!', effect: '+1 Fire Damage. Always inflicts Fire Affliction 1 if you deal damage to a target' },
  { title: 'Toasty', effect: '+5 Damage when you attack a target that is on fire' },
  { title: 'Thanks For All The Fish!', effect: '+3 Accuracy against fish, or other aquatic targets' },
  { title: 'Eat The Elephant', effect: '+2 to Checks made to fix "Problems," in society' },
  { title: 'Two Hops This Time', effect: '+2 Speed while your Ultimate is active' },
  { title: 'Roller Derby Queen', effect: '+3 to all Checks while rollerblading' },
  { title: 'Doomsday Scenario', effect: 'If you are Downed, you may choose to explode, dealing 1000 Kinetic/Fire damage to everything within 100 Squares. Obviously, you die.' },
  { title: 'I’m Just Confused', effect: '+1 to Checks made to end a Condition' },
  { title: 'Who Shot Me?', effect: 'You’re a deputy, somewhere. +1 Accuracy with this weapon' },
  { title: 'Darkblade', effect: '+2 HP when you slay a flesh-and-blood enemy' },
  { title: 'Big Swing, Big Muscles', effect: '+10 Health Points' },
  { title: 'Break My Bones', effect: 'If you Lootbreak this weapon, you may also break one of the bones in your body. If you do, you take 10 True Damage, and all adjacent enemies take 20 True Damage' },
  { title: 'SupahHot Stick', effect: 'You can transform this weapon at will to a superhot blade of pure plasma. +1d8 Plasma Damage' },
  { title: 'Kill, Kill, Kill!', effect: 'You have a hidden Style Skill. When you stylishly kill an enemy, you gain +1 Style, and +1 Speed until the end of your current turn' },
  { title: 'Pool Noodle', effect: 'This weapon looks like a whimsical pool noodle. It doesn’t affect the statistics, but you gain +5 Fun' },
  { title: 'Make It Thunder!', effect: 'When you kill an enemy, adjacent enemies take 1d10 Kinetic Damage. If any enemies die to this effect, they drop +1 Loot Piles' },
  { title: 'Covered In Stickers', effect: 'This weapon is covered in stickers. +3 Diplomacy with children and anarchists' },
  { title: 'I’M FEARING AGAIN', effect: '+2 to Checks made to avoid or end the Spooked Condition. +5 if the origin of the Condition is from a Clown' },
  { title: 'WAR CRIES', effect: 'I’m going to commit various war crimes! +20 Gold per war crime committed' },
  { title: 'Loot Gobby', effect: '+5 Gold whenever you open a cache, treasure chest, or other loot-giving container' },
  { title: 'Feet Finder', effect: '+2 Accuracy against enemies not wearing shoes' },
  { title: 'Chat, Is This Real?', effect: '+2 Search, +5 if you are being helped by a large community' },
  { title: 'Excessive Violence', effect: 'Defeating a target with this weapon produces an unfathomable amount of gore. +1 Diplomacy, +3 if made to intimidate' },
  { title: 'He’s Brucing Out!', effect: '-2 Grit, -2 Athletics, +2 World, +2 Tech, +2 Search' },
  { title: 'Weirdly Specific', effect: '+2 Damage against dogs and dog-like creatures, +50 damage against Cocker Spaniels' },
  { title: 'Vending Vows Vengeance', effect: 'Vending machines have a 5% chance of giving any item for free, but a 15% to fall on you, dealing 2d20 True Damage' },
  { title: 'Acceleration', effect: 'All enemies deal +10 True damage to you, but you deal +15 True damage back' },
  { title: 'Cockroach', effect: 'If you would be downed, instead regain half of your HP total. This weapon is then permanently destroyed' },
  { title: 'Big Win', effect: 'This weapon gains +2 of each damage type, including True Damage' },
];
